name: Python application

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      id: pytest
      run: |
        pytest
        echo "::set-output name=pytest-success::true" # Set an output flag if pytest succeeds

  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    needs: build

    if: ${{ needs.build.result == 'success' && steps.pytest.outputs.pytest-success == 'true' }}

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          remote-host: ${{ secrets.HOST_DNS }}
          remote-user: ${{ secrets.USERNAME }}
          local-path: '.' # Upload the entire repository
          remote-path: '/var/www/html/' # Destination on the remote server
