name: Python application

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
          pytest

          deploy:
            name: Deploy to EC2 on master branch push
            runs-on: ubuntu-latest
        
            steps:
              - name: Checkout the files
                uses: actions/checkout@v2
        
              - name: Deploy to Server
                uses: easingthemes/ssh-deploy@v2
                with:
                  ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
                  remote-host: ${{ secrets.HOST_DNS }}
                  remote-user: ${{ secrets.USERNAME }}
                  local-path: '.' 
                  remote-path: '/var/www/html/'
                  args: '-o StrictHostKeyChecking=no'
